title: LocalKeyRemapper
description: A native, privacy-first, security-first and accessibility-first keyboard remapper for macOS.

url: "https://localkeyremapper.github.io"
baseurl: ""

exclude:
  - README.md